title: Luyao Sun
# Comment out url when working locally to resolve base urls correctly
url: https://luyao-leo-sun.github.io

# Owner/author information
owner:
  name: Luyao Sun
  avatar: luyao-sun.jpg
  email: luyaosun@link.cuhk.edu.cn
  github: Luyao-Leo-Sun
  linkedin: luyao-sun-53bb0b430
  scholar: https://scholar.google.com/citations?user=6Zs-CPcAAAAJ
  researchgate: https://www.researchgate.net/profile/Luyao-Sun-6
  instagram: luyao0514
  bilibili: 26315629

# https://search.google.com/search-console/ownership
google_verify: ""

# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Beyond Research
    url: /hobbies/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
